### ISSUE TITLE
Computer crashes after a few hours

### ISSUE THREAD

**Issue by EatMyWeani** [RS117/RLHD#170]
Computer randomly turns off and back on after a few hours of using HD plugin. Plugin runs seemingly completely fine up until that point, then crashes when it's about to load a new area in game. 

I played a few days without HD with no problems so I'm assuming it's a problem with HD and my computer together. Then I turned all HD settings down/off slowly after each crash and even with them all turned down to lowest settings or off, my computer still crashes. I didn't have any crashes for days without the HD plugin and I get multiple per day with it. 

Specs;
Windows 10 pro 64-bit 10.0 build 19042
Intel core i7-7700k cpu
16 gb ram
AMD radeon rx 480 gpu
     driver version: 30.0.13017.5006

I checked my runelite logs and there aren't any logs at the time of crashing, probably because it's a full computer crash, not just Runelite.

**Comment by Fraser-Watson** [comment]
This sounds more like an instability with your system rather than plugin itself. A couple of things you can try:
  
- Update your graphics drivers
- Run a CPU/GPU stress test to rule out any system instability
- Run a memory test

It may also be a problem with your PSU. If it gets too hot, it will trip out and shut your system down to protect itself.

**Comment by EatMyWeani** [comment]
I'll run the tests. I wanna note that it only happens with rl running the
hd plugin though. It doesn't matter if rl is all I'm playing or if I have
it in the background and I play other seemingly more stressed games like
Rust often. I had also previously checked my task manager periodically
while playing rl and the CPU, gpu, and power consumption were all fairly
low. Below 40% with normal power usage. They were high before turning down
shader settings, but I crashed either way.

**Comment by Hoodz** [comment]
I have since some time the same issues, however I have the error. This makes my pc shut down too

2022-01-07 17:32:10 [Client] INFO  rs117.hd.HdPlugin - Using device: NVIDIA GeForce RTX 3070/PCIe/SSE2
2022-01-07 17:32:10 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6.0 NVIDIA 497.29
2022-01-07 18:00:58 [Client] ERROR injected-client - Game crash: null
com.jogamp.opengl.GLException: Error swapping buffers
	at jogamp.opengl.windows.wgl.WindowsWGLDrawable.swapBuffersImpl(WindowsWGLDrawable.java:93)
	at jogamp.opengl.GLDrawableImpl.swapBuffers(GLDrawableImpl.java:88)
	at rs117.hd.HdPlugin.drawFrame(HdPlugin.java:1995)
	at rs117.hd.HdPlugin.lambda$draw$10(HdPlugin.java:1491)
	at rs117.hd.HdPlugin.invokeOnMainThread(HdPlugin.java:2549)
	at rs117.hd.HdPlugin.draw(HdPlugin.java:1491)
	at am.onPost(GameEngine.java:90)
	at am.t(GameEngine.java)
	at am.run(GameEngine.java:316)
	at java.base/java.lang.Thread.run(Thread.java:834)
