### ISSUE TITLE
ArrayOutOfBoundsException when running from baronite rocks to the anvil

### ISSUE THREAD

**Issue by Im2be** [RS117/RLHD#234]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**

**To Reproduce**
Can't reproduce, happened only once. Ran from the barronite rocks to the west of the anvil towards the anvil and crashed on the tile of the image.

**Expected behavior**
Hard-crashed the game while you expect it to not do that.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/9745984/156588531-b7dc3019-5250-4319-93ff-9e079872e42b.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.8.2
 - OpenOSRS version: 2.20.2
 - OpenOSRS Launcher version: 2.2.0

**Additional context**
```
2022-03-03 15:46:15 [Client] ERROR injected-client - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 291 out of bounds for length 288
	at rs117.hd.ModelData.getColorForFace(ModelPusher.java:24)
	at rs117.hd.ModelPusher.getVertexDataForFace(ModelPusher.java:126)
	at rs117.hd.ModelPusher.pushModel(ModelPusher.java:97)
	at rs117.hd.HdPlugin.draw(HdPlugin.java:2475)
	at net.runelite.client.callback.Hooks.renderDraw(Hooks.java:577)
	at gn.au(Scene.java:990)
	at gn.draw(Scene.java)
	at gn.ad(Scene.java:393)
	at jt.gn(class282.java:4471)
	at ka.ii(Skills.java:9860)
	at ka.ii(Skills.java:9891)
	at ds.ij(UserComparator5.java:9749)
	at client.ga(Client.java:4198)
	at client.copy$draw(Client.java:1036)
	at client.ap(Client.java:1803)
	at al.j(GameEngine.java:370)
	at al.run(GameEngine.java:324)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Im2be** [comment]
Crashed again with same index:

```
2022-03-03 15:51:53 [Client] ERROR injected-client - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: Index 291 out of bounds for length 288
	at rs117.hd.ModelData.getColorForFace(ModelPusher.java:24)
	at rs117.hd.ModelPusher.getVertexDataForFace(ModelPusher.java:126)
	at rs117.hd.ModelPusher.pushModel(ModelPusher.java:97)
	at rs117.hd.HdPlugin.draw(HdPlugin.java:2475)
	at net.runelite.client.callback.Hooks.renderDraw(Hooks.java:577)
	at gn.au(Scene.java:990)
	at gn.draw(Scene.java)
	at gn.ad(Scene.java:393)
	at jt.gn(class282.java:4471)
	at ka.ii(Skills.java:9860)
	at ka.ii(Skills.java:9891)
	at ds.ij(UserComparator5.java:9749)
	at client.ga(Client.java:4198)
	at client.copy$draw(Client.java:1036)
	at client.ap(Client.java:1803)
	at al.j(GameEngine.java:370)
	at al.run(GameEngine.java:324)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by xxEzri** [comment]
OpenOSRS is a cheat client which is not allowed by Jagex or supported by the Runelite/117 teams.

https://twitter.com/jagextyran/status/1358801848166137856?lang=en-GB

**Comment by sosodev** [comment]
Yes, please use Runelite instead of OpenOSRS. Also, this is already fixed it just hasn't been released yet.
