### ISSUE TITLE
ArrayIndexOutOfBoundsException Index 4370

### ISSUE THREAD

**Issue by persiden** [RS117/RLHD#258]
From latest runelite client I am getting the following error that doesn't allow me to launch runelite: 

2022-03-16 10:18:43 [Client] INFO  rs117.hd.HdPlugin - Client is 64-bit
2022-03-16 10:18:45 [Client] ERROR client-patch - Client error: null
java.lang.ArrayIndexOutOfBoundsException: Index 4370 out of bounds for length 4353
	at kq.qh(kq.java:205)
	at gy.c(gy.java:54)
	at gw.s(gw.java:72)
	at gw.load(gw.java)
	at rs117.hd.TextureManager.allTexturesLoaded(TextureManager.java:281)
	at rs117.hd.TextureManager.initTextureArray(TextureManager.java:51)
	at rs117.hd.HdPlugin.drawFrame(HdPlugin.java:1618)
	at rs117.hd.HdPlugin.lambda$draw$10(HdPlugin.java:1510)
	at rs117.hd.HdPlugin.invokeOnMainThread(HdPlugin.java:2580)
	at rs117.hd.HdPlugin.draw(HdPlugin.java:1510)
	at al.o(al.java:50178)
	at al.run(al.java:325)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xxEzri** [comment]
"this is from the botched game update earlier" - Adam
