### ISSUE TITLE
Can't load library: \natives\windows-amd64\\gluegen_rt.dll

### ISSUE THREAD

**Issue by archubbuck** [RS117/RLHD#27]
```
2021-09-13 14:53:55 [Client] ERROR rs117.hd.HdPlugin - Error starting HD plugin
java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Adam\AppData\Local\OpenOSRS\natives\windows-amd64\\gluegen_rt.dll
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
	at com.jogamp.common.os.Platform$1.run(Platform.java:321)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:154)
	at rs117.hd.HdPlugin.lambda$startUp$2(HdPlugin.java:438)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:116)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:199)
	at client.draw(Client.java:1552)
	at client.aq(Client.java)
	at at.b(GameEngine.java:406)
	at at.run(GameEngine.java:360)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-09-13 14:53:55 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
	at rs117.hd.HdPlugin.lambda$shutDown$4(HdPlugin.java:624)
	at net.runelite.client.callback.ClientThread.lambda$invoke$1(ClientThread.java:65)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:78)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:63)
	at rs117.hd.HdPlugin.shutDown(HdPlugin.java:570)
	at rs117.hd.HdPlugin.lambda$startUp$2(HdPlugin.java:557)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:116)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:199)
	at client.draw(Client.java:1552)
	at client.aq(Client.java)
	at at.b(GameEngine.java:406)
	at at.run(GameEngine.java:360)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-09-13 14:53:55 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
	at rs117.hd.HdPlugin.lambda$shutDown$4(HdPlugin.java:624)
	at net.runelite.client.callback.ClientThread.lambda$invoke$1(ClientThread.java:65)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:116)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:199)
	at client.draw(Client.java:1552)
	at client.aq(Client.java)
	at at.b(GameEngine.java:406)
	at at.run(GameEngine.java:360)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-09-13 14:55:52 [Thread-21] WARN  net.runelite.client.util.LinkBrowser - Failed to open Desktop#browse https://github.com/RS117/RLHD/tree/8f85189d125f376bcde38cf41e8e1495dd0bd728
java.io.IOException: Failed to open https://github.com/RS117/RLHD/tree/8f85189d125f376bcde38cf41e8e1495dd0bd728. Error message: No application is associated with the specified file for this operation.

	at java.desktop/sun.awt.windows.WDesktopPeer.ShellExecute(Unknown Source)
	at java.desktop/sun.awt.windows.WDesktopPeer.browse(Unknown Source)
	at java.desktop/java.awt.Desktop.browse(Unknown Source)
	at net.runelite.client.util.LinkBrowser.attemptDesktopBrowse(LinkBrowser.java:156)
	at net.runelite.client.util.LinkBrowser.lambda$browse$0(LinkBrowser.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)
2021-09-13 14:55:52 [Thread-21] WARN  net.runelite.client.util.LinkBrowser - LinkBrowser.browse() could not open https://github.com/RS117/RLHD/tree/8f85189d125f376bcde38cf41e8e1495dd0bd728
```

**Comment by jgbdgch2** [comment]
I'm having the same issue. Did you find a fix?

**Comment by archubbuck** [comment]
> I'm having the same issue. Did you find a fix?

No 👎

**Comment by JoaoAreias** [comment]
Same issue here :/
