### ISSUE TITLE
Client crashes because of ArrayOutOfBoundsException

### ISSUE THREAD

**Issue by decramer16** [RS117/RLHD#281]
After playing for 20 minutes, the client will crash and will have to be closed.

**To Reproduce**
1. Play for a bit (I was at the clocktower when I crashed, coming from Fossil Island)
2. Client crashes
3. Close Runelite

**Expected behavior**
No crash

**Environment (please complete the following information):**

- OS: Windows
- RuneLite version: [e.g 1.8.18.4]
- Launcher version: [e.g 2.3.0]

**Additional context**
Client Log with Bug crash: [client.log](https://github.com/RS117/RLHD/files/8571950/client.log)

**Exact error:**
`2022-04-27 07:57:12 [Client] INFO  rs117.hd.HdPlugin - Using device: NVIDIA GeForce GTX 1070/PCIe/SSE2
2022-04-27 07:57:12 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6.0 NVIDIA 511.23
2022-04-27 07:57:12 [Client] INFO  rs117.hd.HdPlugin - Client is 64-bit
2022-04-27 08:09:26 [Client] ERROR client-patch - Client error: null
java.lang.ArrayIndexOutOfBoundsException: Index 19 out of bounds for length 16
	at rs117.hd.ModelData.getColorForFace(ModelPusher.java:24)
	at rs117.hd.ModelPusher.getVertexDataForFace(ModelPusher.java:126)
	at rs117.hd.ModelPusher.pushModel(ModelPusher.java:97)
	at rs117.hd.HdPlugin.draw(HdPlugin.java:2478)
	at client.ww(client.java:42125)
	at hv.au(hv.java:1162)
	at hv.uj(hv.java)
	at hv.ab(hv.java:18376)
	at gw.gq(gw.java:4670)
	at jr.jp(jr.java:10333)
	at jr.jp(jr.java:10364)
	at es.jl(es.java:10222)
	at client.gu(client.java:4321)
	at client.h(client.java:1025)
	at ao.g(ao.java:385)
	at ao.run(ao.java:339)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by xxEzri** [comment]
#279

**Comment by xxEzri** [comment]
> 

No it is the same thing

"java.lang.ArrayIndexOutOfBoundsException: Index 19 out of bounds for length 16 at rs117.hd.ModelData.getColorForFace(ModelPusher.java:24)"

vs

"java.lang.ArrayIndexOutOfBoundsException: Index 291 out of bounds for length 288
at rs117.hd.ModelData.getColorForFace(ModelPusher.java:24)"

**Comment by decramer16** [comment]
I see. Does disabling model caching option prevent this specific crash too?

**Comment by xxEzri** [comment]
> 

Yeah, that might be a good option though it's unfortunate. I think this is the only known crash and it definitely only happens with the live version of 117HD and model caching turned on, but these plugins will never be quite as bulletproof as the raw game.

**Comment by decramer16** [comment]
> 

Awesome! Thank you!

**Comment by sosodev** [comment]
This should be fixed as of the latest update. You should consider re-enabling model caching if you have it disabled as it greatly improves performance in many scenes. :slightly_smiling_face:
