### ISSUE TITLE
Out of memory crash on Kephri room in raids 3

### ISSUE THREAD

**Issue by Crecket** [RS117/RLHD#336]
**Describe the bug**
It has happened twice now where at some point in the Kephri boss room around the time when the parasite eggs spawn and tons of other stuff shows up my FPS gets lower and lower until eventually Runelite just freezes up and crashes. Turning off this  plugin made it so I had 0 issues afterwards so I assume it is related to RLHD

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.8.32
 - Launcher version: 2.1.0

**Additional context**
Error log for the two times it crashed, both times when you see out of memmory errors in the logs is when my client crashed
```
2022-08-24 19:10:53 [Client] INFO  c.f.controller.FlippingPlugin - Crecket has just logged in!
2022-08-24 19:10:53 [Client] INFO  c.f.controller.FlippingPlugin - starting slot timers on login
2022-08-24 19:12:37 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
2022-08-24 19:49:29 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.killsperhour.FileReadWriter.bossNameMatcher(FileReadWriter.java:171)
	at com.killsperhour.FileReadWriter.lootReceived(FileReadWriter.java:210)
	at com.killsperhour.KphPlugin.onLootReceived(KphPlugin.java:223)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.plugins.loottracker.LootTrackerPlugin.addLoot(LootTrackerPlugin.java:609)
	at net.runelite.client.plugins.loottracker.LootTrackerPlugin.addLoot(LootTrackerPlugin.java:595)
	at net.runelite.client.plugins.loottracker.LootTrackerPlugin.onNpcLootReceived(LootTrackerPlugin.java:626)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.game.LootManager.processNpcLoot(LootManager.java:323)
	at net.runelite.client.game.LootManager.onNpcDespawned(LootManager.java:139)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:179)
	at ct.fv(ct.java:22162)
	at da.hf(da.java:8170)
	at client.gd(client.java:7213)
	at client.ez(client.java:2964)
	at client.g(client.java:1057)
	at ab.ya(ab.java:362)
	at ab.run(ab.java:341)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-08-24 20:07:35 [D3D Screen Updater] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
2022-08-24 20:07:35 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.MultipleGradientPaintContext.calculateSingleArrayGradient(Unknown Source)
	at java.desktop/java.awt.MultipleGradientPaintContext.calculateLookupData(Unknown Source)
	at java.desktop/java.awt.MultipleGradientPaintContext.<init>(Unknown Source)
	at java.desktop/java.awt.LinearGradientPaintContext.<init>(Unknown Source)
	at java.desktop/java.awt.LinearGradientPaint.createContext(Unknown Source)
	at java.desktop/sun.java2d.pipe.AlphaPaintPipe.startSequence(Unknown Source)
	at java.desktop/sun.java2d.pipe.AAShapePipe.renderTiles(Unknown Source)
	at java.desktop/sun.java2d.pipe.AAShapePipe.renderPath(Unknown Source)
	at java.desktop/sun.java2d.pipe.AAShapePipe.draw(Unknown Source)
	at java.desktop/sun.java2d.pipe.PixelToParallelogramConverter.draw(Unknown Source)
	at java.desktop/sun.java2d.pipe.ValidatePipe.draw(Unknown Source)
	at java.desktop/sun.java2d.SunGraphics2D.draw(Unknown Source)
	at org.pushingpixels.substance.api.painter.border.StandardBorderPainter.paintBorder(StandardBorderPainter.java:97)
	at org.pushingpixels.substance.api.painter.border.CompositeBorderPainter.paintBorder(CompositeBorderPainter.java:92)
	at org.pushingpixels.substance.internal.utils.ButtonBackgroundDelegate.createBackgroundImage(ButtonBackgroundDelegate.java:312)
	at org.pushingpixels.substance.internal.utils.ButtonBackgroundDelegate.getFullAlphaBackground(ButtonBackgroundDelegate.java:227)
	at org.pushingpixels.substance.internal.utils.ButtonBackgroundDelegate.updateBackground(ButtonBackgroundDelegate.java:355)
	at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.paint(SubstanceButtonUI.java:409)
	at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.update(SubstanceButtonUI.java:572)
	at java.desktop/javax.swing.JComponent.paintComponent(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JLayeredPane.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
2022-08-24 20:07:35 [Trident pulse source thread] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
2022-08-24 20:07:36 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
2022-08-24 20:07:37 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
2022-08-24 20:07:53 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
2022-08-24 20:08:13 [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite�1.8.32 (launcher version 2.1.0) starting up, args: none
2022-08-24 20:08:14 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2022-08-24 20:08:14 [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2022-08-24 20:08:14 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 2918248169.236
2022-08-24 20:08:16 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "mlm-upper-level-markers" version "1.3" commit "eebf4482339cd1f2c0706341ebc849d2b7d5802e"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bank-tag-layouts" version "1.4.18" commit "5a72db686c63e6d32f69bb54d1d7317926649544"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ultimate-nmz" version "e0bc48dd" commit "e0bc48dd066a4e8155fef55cec196ead9c4f6e09"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "cox-special-loot-hider" version "4838f75f" commit "4838f75fb86f32b7b517b94baca94b92b7f2ed0e"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tasks-tracker" version "689115c0" commit "689115c06e84ee958791e62cab52299198f0d61a"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zom-leftclick-dropper" version "1.6" commit "a58e8acb5dad2a2b758083d839a0de83cc8c3ec2"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.4.1" commit "d2d60e23b6df89aa48529ed65e4e3e898a7a3511"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "wilderness-multi-lines" version "1.1" commit "4bd8dfdf9a87043bd90bd34ce00298e57f7cdde8"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "cox-scouter-external" version "1.2.5" commit "fa8c71ac0641f35f337ed1decd15b76339b771d1"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "cox-additions" version "9d372557" commit "9d372557a4269b5de1d10763c394da2934df22d1"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tempoross" version "1.2" commit "af72eacca6df48b132232cb4dd5775b225fa2e5e"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "hotkeyable-menu-swaps" version "2.0.1" commit "0e50cdf51f39c8bb17c8c69a9f2944074dcb25c2"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "watson-clue-tracker" version "1.0.7" commit "7862ef80610a8974ef2c3f8ec1273e21cb8372e1"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.1.3" commit "28e091dee610fdf682cdad198fbe5def841c134c"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "supplies-tracker" version "3.0.0" commit "067f98817eeb98c6e34fadeb7f1f7bd074cb964c"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bot-detector" version "1.3.8" commit "978770a8fdd52088f36b7836ed6c9da35f47b634"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "raid-reloader" version "415a4b71" commit "415a4b71a6f94f9f10345f5c825ab1109bc7cb07"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "kph-tracker" version "1.8.5" commit "37786f0783bdf4dc0fda6d899050b9b791e73622"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tob-notice-board" version "1.1" commit "40af4de25e32af05a1ce15befd62d4afbe6af696"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "guardians-of-the-rift-helper" version "1.01" commit "9f2925a9dde2dcd2fec8f33188dfba58681206ad"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ping-grapher" version "1.4.1" commit "1e32cca29af8e0c814dd08dd98c5cf8957c4b6ad"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "inventory-setups" version "v1.14" commit "1b4833165c7c7059a711ef3e2ac1606d93e98b1d"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "crab-stun-timers" version "b0e7ad22" commit "b0e7ad22a6018fed3cdcd105d6a1873a242e75e3"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "door-kicker" version "1.0.1" commit "9d078ca73f670d14b23bbb776ffd75075bec69f3"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "quest-helper" version "3.1.0" commit "30011e7063d0b81d6990d97bdeef3ab008884d40"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "flipping-utilities" version "1.4.1" commit "089d694bdda1d52c85c6f79cfdd70f6f4c954776"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.2" commit "e8315a9eb364fbc5e689ac3b732c96c5854aa4ef"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "spawnpredictor" version "1.0.1" commit "87a1f7dcbb3f590f8e1c823273146b35e669091e"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "visual-metronome" version "1.4.2" commit "db5ae9cc34ae386343f5aef20ba8ef968bbb4bf1"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "theatre-of-blood-stats" version "1.3.1" commit "2c1d2806f2808ed592ebb939fc278ae7fcb2b153"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "equipment-inspector" version "1.2" commit "c0018d299bb4a3dd4ef971a72bfdc776a42f0ff8"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "crab-solver" version "1.2" commit "ae05921462c576f0c45ce24ee4bbfc9f631cf1dd"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "path-marker" version "1.02" commit "4c78607562b6fd965a7bebb9b5af6ef15be4c571"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "action-progress" version "c13d6723" commit "c13d6723cf787e96d2c1354c35f798ca4c637d0b"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fashionscape" version "1.1.16" commit "980749dd68cac290887494af0af1472cc5e25d77"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "loot-logger" version "3.2.2" commit "43493ded00d221da69829baba7313b119981dd47"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bank-xp-value" version "1.2.1" commit "d4f893870588c8336ee4a662bf48e7fb6b67e146"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fish-barrel" version "1.1" commit "1dc5eb4fba8773a6c65e96e940ad333ab785b100"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "cox-analytics" version "1.0.0" commit "0551c1a3bfb6871548ee9c38b3a6746f8ab3758e"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "butler" version "4d73e6ca" commit "4d73e6ca49d97433c726489fcd5e8a07b3d9a013"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "maxhitplugin" version "23d328cb" commit "23d328cb160dd471431fd88fbb8268b8f01f01a2"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tob-healthbars" version "b9d58dd8" commit "b9d58dd864ce33a23b34eac91865bdb1521a379a"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "temple-osrs" version "cbc997b7" commit "cbc997b7495d358c31a3847a00ce3633abbeedd7"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "chatbox-opacity" version "dbee9ba4" commit "dbee9ba4e138cae2467354fc169d9c34dcac3162"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ticktracker" version "1.1" commit "11d935fc4697df198acf419ddecd445517303418"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "collection-log" version "2.2.3" commit "52bb973481b3ebc06fb9a84eae15de0d0a669b19"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "optimal-quest-guide" version "cbafa444" commit "cbafa4440bc08f6f93727730cd27fe5f15083d87"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "the-gauntlet" version "1.0.0" commit "703ddba102f0c3887c4e25c772d3c5b22de193a8"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "runewatch" version "2.2.1" commit "2573e1d9fd6d47c69cf5bf3ef1457d0c9969cbfc"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "wikisync" version "2.0" commit "8246ef597be7554010737e8c47559b23d689410f"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "raid-data-tracker" version "1.4.2" commit "28c1a040e04928ac0e7a82d352894a2a611793c6"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "one-click-summer-garden" version "2.2.0" commit "11c0f4d7ed85b058121a4568c94b34bb94399379"
2022-08-24 20:08:17 [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "skills-tab-progress-bars" version "1.2" commit "9ea27934275a809456d7bb6ebd636009787f94f3"
2022-08-24 20:08:18 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2022-08-24 20:08:19 [AWT-EventQueue-0] INFO  n.r.taskstracker.TasksTrackerPlugin - Tasks Tracker started!
2022-08-24 20:08:20 [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user Crecket.
2022-08-24 20:08:20 [AWT-EventQueue-0] INFO  c.f.controller.RecipeHandler - Successfully loaded recipes
2022-08-24 20:08:21 [Client] INFO  c.f.controller.DataHandler - Initiating load on startup
2022-08-24 20:08:21 [Client] INFO  c.f.db.TradePersister - flipping directory already exists so it's not being created
2022-08-24 20:08:21 [Client] INFO  c.f.controller.DataHandler - Fetching account wide data
2022-08-24 20:08:21 [Client] INFO  c.f.controller.DataHandler - successfully loaded account wide data
2022-08-24 20:08:21 [Client] INFO  c.f.db.TradePersister - not loading data from file: accountwide.json
2022-08-24 20:08:21 [Client] INFO  c.f.db.TradePersister - loading data for Crecket
2022-08-24 20:08:21 [Client] INFO  c.f.controller.DataHandler - Finished loading and preparing all accounts
2022-08-24 20:08:21 [Client] INFO  c.f.controller.FlippingPlugin - changing view to Accountwide
2022-08-24 20:08:21 [Client] INFO  c.f.jobs.WikiDataFetcherJob - started wiki fetching job
2022-08-24 20:08:21 [Client] INFO  c.f.jobs.SlotSenderJob - started slot sender job
2022-08-24 20:08:21 [Client] INFO  c.f.controller.ApiAuthHandler - no jwt stored locally, not attempting to check existing jwt
2022-08-24 20:08:21 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 8153ms. Uptime: 10181ms
2022-08-24 20:08:22 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,1059,110,1234x945,invalid,layout=java.awt.BorderLayout,title=RuneLite,resizable,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1234x945,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@26bed029,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2022-08-24 20:08:22 [Client] INFO  rs117.hd.HdPlugin - Using device: NVIDIA GeForce RTX 2070/PCIe/SSE2
2022-08-24 20:08:22 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6.0 NVIDIA 516.94
2022-08-24 20:08:22 [Client] INFO  rs117.hd.HdPlugin - Client is 64-bit
2022-08-24 20:08:22 [pool-8-thread-1] INFO  c.f.jobs.CacheUpdaterJob - starting cache updator job!
2022-08-24 20:08:22 [Client] INFO  rs117.hd.scene.lighting.LightConfig - Loaded 1577 lights
2022-08-24 20:08:33 [Client] INFO  c.f.controller.FlippingPlugin - Crecket has just logged in!
2022-08-24 20:08:33 [Client] INFO  c.f.controller.FlippingPlugin - changing view to Crecket
2022-08-24 20:08:33 [Client] INFO  c.f.controller.FlippingPlugin - starting slot timers on login
2022-08-24 20:15:01 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: Index 38 out of bounds for length 28
	at com.suppliestracker.SuppliesTrackerPlugin.processInvChange(SuppliesTrackerPlugin.java:866)
	at com.suppliestracker.SuppliesTrackerPlugin.onItemContainerChanged(SuppliesTrackerPlugin.java:716)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:69)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:195)
	at client.of(client.java:17085)
	at client.g(client.java)
	at ab.ya(ab.java:362)
	at ab.run(ab.java:341)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-08-24 20:23:15 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.killsperhour.FileReadWriter.bossNameMatcher(FileReadWriter.java:171)
	at com.killsperhour.FileReadWriter.lootReceived(FileReadWriter.java:210)
	at com.killsperhour.KphPlugin.onLootReceived(KphPlugin.java:223)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.plugins.loottracker.LootTrackerPlugin.addLoot(LootTrackerPlugin.java:609)
	at net.runelite.client.plugins.loottracker.LootTrackerPlugin.addLoot(LootTrackerPlugin.java:595)
	at net.runelite.client.plugins.loottracker.LootTrackerPlugin.onNpcLootReceived(LootTrackerPlugin.java:626)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.game.LootManager.processNpcLoot(LootManager.java:323)
	at net.runelite.client.game.LootManager.onNpcDespawned(LootManager.java:139)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:179)
	at ct.fv(ct.java:22162)
	at da.hf(da.java:8170)
	at client.gd(client.java:7213)
	at client.ez(client.java:2964)
	at client.g(client.java:1057)
	at ab.ya(ab.java:362)
	at ab.run(ab.java:341)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-08-24 20:30:17 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at net.runelite.api.coords.WorldArea.canTravelInDirection(WorldArea.java:275)
	at com.pathmarker.PathMarkerPlugin.updateCheckpointTiles(PathMarkerPlugin.java:550)
	at com.pathmarker.PathMarkerPlugin.onGameTick(PathMarkerPlugin.java:1205)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:197)
	at client.of(client.java:17085)
	at client.g(client.java)
	at ab.ya(ab.java:362)
	at ab.run(ab.java:341)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-08-24 20:34:29 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
2022-08-24 20:34:42 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.killsperhour.FileReadWriter.bossNameMatcher(FileReadWriter.java:171)
	at com.killsperhour.FileReadWriter.lootReceived(FileReadWriter.java:210)
	at com.killsperhour.KphPlugin.onLootReceived(KphPlugin.java:223)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.plugins.loottracker.LootTrackerPlugin.addLoot(LootTrackerPlugin.java:609)
	at net.runelite.client.plugins.loottracker.LootTrackerPlugin.addLoot(LootTrackerPlugin.java:595)
	at net.runelite.client.plugins.loottracker.LootTrackerPlugin.onWidgetLoaded(LootTrackerPlugin.java:773)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:179)
	at client.fw(client.java:31536)
	at js.bb(js.java:5003)
	at bq.jk(bq.java:11774)
	at client.gd(client.java:6738)
	at client.ez(client.java:2964)
	at client.g(client.java:1057)
	at ab.ya(ab.java:362)
	at ab.run(ab.java:341)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-08-24 21:22:53 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOfRange(Unknown Source)
	at rs117.hd.model.ModelPusher.getColorsForModel(ModelPusher.java:276)
	at rs117.hd.model.ModelPusher.getCachedModelData(ModelPusher.java:264)
	at rs117.hd.model.ModelPusher.pushModel(ModelPusher.java:78)
	at rs117.hd.HdPlugin.draw(HdPlugin.java:2412)
	at client.zf(client.java:56957)
	at gy.lb(gy.java:1096)
	at gy.xv(gy.java)
	at gy.tn(gy.java:63306)
	at bb.fi(bb.java:4621)
	at ff.if(ff.java:9899)
	at ff.if(ff.java:9930)
	at bb.iv(bb.java:9788)
	at client.fr(client.java:4391)
	at client.ar(client.java:1128)
	at ab.e(ab.java:388)
	at ab.run(ab.java:342)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-08-24 21:23:12 [Trident pulse source thread] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
2022-08-24 21:23:12 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/sun.java2d.marlin.IntArrayCache.createArray(Unknown Source)
	at java.desktop/sun.java2d.marlin.IntArrayCache$Reference.<init>(Unknown Source)
	at java.desktop/sun.java2d.marlin.IntArrayCache.createRef(Unknown Source)
	at java.desktop/sun.java2d.marlin.DRendererContext.newCleanIntArrayRef(Unknown Source)
	at java.desktop/sun.java2d.marlin.DRenderer.<init>(Unknown Source)
	at java.desktop/sun.java2d.marlin.DRendererContext.<init>(Unknown Source)
	at java.desktop/sun.java2d.marlin.DRendererContext.createContext(Unknown Source)
	at java.desktop/sun.java2d.marlin.DMarlinRenderingEngine$1.newContext(Unknown Source)
	at java.desktop/sun.java2d.marlin.DMarlinRenderingEngine$1.newContext(Unknown Source)
	at java.desktop/sun.java2d.ReentrantContextProviderTL.acquire(Unknown Source)
	at java.desktop/sun.java2d.marlin.DMarlinRenderingEngine.getRendererContext(Unknown Source)
	at java.desktop/sun.java2d.marlin.DMarlinRenderingEngine.getAATileGenerator(Unknown Source)
	at java.desktop/sun.java2d.pipe.AAShapePipe.renderPath(Unknown Source)
	at java.desktop/sun.java2d.pipe.AAShapePipe.draw(Unknown Source)
	at java.desktop/sun.java2d.pipe.PixelToParallelogramConverter.draw(Unknown Source)
	at java.desktop/sun.java2d.pipe.ValidatePipe.draw(Unknown Source)
	at java.desktop/sun.java2d.SunGraphics2D.draw(Unknown Source)
	at org.pushingpixels.substance.api.painter.border.StandardBorderPainter.paintBorder(StandardBorderPainter.java:97)
	at org.pushingpixels.substance.api.painter.border.DelegateBorderPainter.paintBorder(DelegateBorderPainter.java:166)
	at org.pushingpixels.substance.api.painter.border.CompositeBorderPainter.paintBorder(CompositeBorderPainter.java:88)
	at org.pushingpixels.substance.internal.utils.ButtonBackgroundDelegate.createBackgroundImage(ButtonBackgroundDelegate.java:312)
	at org.pushingpixels.substance.internal.utils.ButtonBackgroundDelegate.getFullAlphaBackground(ButtonBackgroundDelegate.java:227)
	at org.pushingpixels.substance.internal.utils.ButtonBackgroundDelegate.updateBackground(ButtonBackgroundDelegate.java:355)
	at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.paint(SubstanceButtonUI.java:409)
	at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.update(SubstanceButtonUI.java:572)
	at java.desktop/javax.swing.JComponent.paintComponent(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
	at java.desktop/javax.swing.JComponent.paint(Unknown Source)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(Unknown Source)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
2022-08-24 21:23:12 [pool-9-thread-1] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
2022-08-24 21:23:12 [D3D Screen Updater] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space

```

**Comment by Xilador** [comment]
Same happens to me EVERY TIME, absolutely frustrating

**Comment by aHooder** [comment]
This was an issue for a while following the release of Tombs of Amascut, but has since been fixed I believe.
