### ISSUE TITLE
Plugin fails to turn on

### ISSUE THREAD

**Issue by Jonxslays** [RS117/RLHD#340]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/RS117/RLHD/search?type=Issues)

**Describe the bug**

There are a few issues i've seen littered around about the plugin disabling immediately, which is what im experiencing - however most of those were related to MACOS in the past, or no GPU.

Everything was working normally yesterday it appeared. This issue occurred, I performed a full system update including runelite, the runescape launcher and kernel, and the issue persists.

**To Reproduce**
1. Enable 117 HD
2. The plugin immediately turns off

**Expected behavior**

The plugin stays enabled.

**Environment (please complete the following information):**
 - OS: Arch Linux Kernel 6.1.27-1-lts
 - RuneLite version: 1.9.15.3
 - Launcher version: 2.6.3

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

Relevant Error in logs:

```sh
2023-05-04 16:05:59 [Client] INFO  rs117.hd.HdPlugin - Using device: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.27-1-lts)
2023-05-04 16:05:59 [Client] INFO  rs117.hd.HdPlugin - Using driver: 4.6 (Compatibility Profile) Mesa 23.0.3
2023-05-04 16:05:59 [Client] INFO  rs117.hd.HdPlugin - Client is 64-bit
2023-05-04 16:05:59 [Client] ERROR rs117.hd.HdPlugin - Error while starting 117HD
rs117.hd.opengl.shader.ShaderException: Compile error while compiling shader: vert.glsl
9:45(2): error: `return' with wrong type int, in function `calculateFogAmount' returning float
Included sources: [
   0: vert.glsl
   1: uniforms/materials.glsl
   2: MATERIAL_COUNT
   3: MATERIAL_GETTER
   4: utils/polyfills.glsl
   5: utils/constants.glsl
   6: SHADOW_MODE
   7: SHADOW_TRANSPARENCY
   8: utils/color_conversion.glsl
   9: utils/fog.glsl
  10: uniforms/camera.glsl
]
	at rs117.hd.opengl.shader.ShaderException.compileError(ShaderException.java:98)
	at rs117.hd.opengl.shader.Shader.compile(Shader.java:92)
	at rs117.hd.HdPlugin.initPrograms(HdPlugin.java:776)
	at rs117.hd.HdPlugin.lambda$startUp$2(HdPlugin.java:546)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:215)
	at client.sm(client.java:36061)
	at client.bd(client.java)
	at bm.ap(bm.java:353)
	at bm.run(bm.java:332)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by Jonxslays** [comment]
UPDATE: After making no changes and coming back today - the plugin just starts normally again. I must assume it was something with my system itself. Closing this issue.
