### ISSUE TITLE
runelite hd not working??

### ISSUE THREAD

**Issue by MFBread** [RS117/RLHD#40]
Downloaded the plugin and doesnt, do anything turns off after you turn it on... is there anything specific to do to make it work?? any help would be appreciated

**Comment by osrsblood** [comment]
It's just got some buggy quirks that need to be worked out yet,  it seems like lots of people are having similar issues with the plugin simply not activating (and throwing an error in your client.log file along the way).  Mine has to do with shader buffers or something.

**Comment by plsleavemealone123** [comment]
having this same problem

**Comment by JorisBlanken** [comment]
> Downloaded the plugin and doesnt, do anything turns off after you turn it on... is there anything specific to do to make it work?? any help would be appreciated

Can you share you latest client.log file? In windows 10 this file is located in %userprofile%. runelite\logs

**Comment by MFBread** [comment]
[client.log](https://github.com/RS117/RLHD/files/7158842/client.log)

**Comment by Paste187** [comment]
Runelite HD will NOT work if you have an intagrated graphics card. The text saying it's conflicting with your GPU isn't refering to the GPU plugin it's your grahics card.

**Comment by JorisBlanken** [comment]
> Runelite HD will NOT work if you have an intagrated graphics card. The text saying it's conflicting with your GPU isn't refering to the GPU plugin it's your grahics card.

See https://github.com/RS117/RLHD/issues/52#issuecomment-920020709

**Comment by gccunha1** [comment]
Hi guys, I see this issue is still open

I have the same problem, yet I do not have an integrated GPU and this plugin worked in the past. suddenly it now turns off imediately when turning it on.

client.log says:

> 2022-03-31 23:23:15 [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
	at rs117.hd.HdPlugin.lambda$shutDown$4(HdPlugin.java:691)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:193)
	at client.ts(client.java:58003)
	at client.ah(client.java)
	at aw.a(aw.java:366)
	at aw.run(aw.java:345)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by xxEzri** [comment]
Your graphics driver is probably wrong / no longer present, what graphics hardware is it?

**Comment by aHooder** [comment]
Are you using the real RuneLite?

**Comment by gccunha1** [comment]
> @[gccunha1](https://github.com/gccunha1) Your graphics driver is probably wrong / no longer present, what graphics hardware is it?

This was a good tip as I hadn't updated the gpu drivers in a while, but I still have the same issue. (I have rebooted after installing the driver aswell). It is an nvidia RTX3060 and I have driver version 512.15 installed

**Comment by gccunha1** [comment]
> Are you using the real RuneLite?

I guess so. Downloaded the windows 64 bit version from the runelite website (runelite.net)
