### ISSUE TITLE
shader storage buffer binding must be less than "GL_MAX_SHADER_STORAGE_BUFFER_....

### ISSUE THREAD

**Issue by osrsblood** [RS117/RLHD#41]
This is the error that is in client.log every time the plugin is tried to start.   windows 7 all drivers up to date (amd 550 rx + i7 3770)  Could be just lack of power cause this hardware is definitely "older".  Although it entirely depends how the plugin was coded seeing as original hd would have ran smooth on much older hardware.     Appreciate all the hard work you've done 117 and continue to do.   Hopefully some of these annoying problems are figured out eventually.  Thanks guys! 

`2021-09-13 16:14:01 [Client] ERROR rs117.hd.HdPlugin - Error starting HD plugin
java.lang.RuntimeException: rs117.hd.ShaderException: ERROR: 0:120: '' : shader storage buffer binding must be less than "GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS" (8)
ERROR: 0:119: '' : shader storage buffer binding must be less than "GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS" (8)
ERROR: 0:124: '' : shader storage buffer binding must be less than "GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS" (8)
ERROR: 0:123: '' : shader storage buffer binding must be less than "GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS" (8)
ERROR: 0:382: 'ssboOffset' : undeclared identifier 
ERROR: 0:384: 'ssboOffset' : undeclared identifier 
ERROR: 0:393: 'thisA' : undeclared identifier 
ERROR: 0:393: 'ssboOffset' : undeclared identifier 
ERROR: 0:393: '[]' : integer expression required 
ERROR: 0:393: 'assign' :  cannot convert from '4-component vector of int' to 'float'
ERROR: 0:394: 'thisB' : undeclared identifier 
ERROR: 0:394: '[]' : integer expression required 
ERROR: 0:394: 'assign' :  cannot convert from '4-component vector of int' to 'float'
ERROR: 0:395: 'thisC' : undeclared identifier 
ERROR: 0:395
	at rs117.hd.HdPlugin.lambda$startUp$0(HdPlugin.java:501)
	at rs117.hd.HdPlugin.invokeOnMainThread(HdPlugin.java:2363)
	at rs117.hd.HdPlugin.lambda$startUp$2(HdPlugin.java:440)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:195)
	at client.tq(client.java:43502)
	at client.aq(client.java)
	at at.b(at.java:406)
	at at.run(at.java:360)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: rs117.hd.ShaderException: ERROR: 0:120: '' : shader storage buffer binding must be less than "GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS" (8)
ERROR: 0:119: '' : shader storage buffer binding must be less than "GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS" (8)
ERROR: 0:124: '' : shader storage buffer binding must be less than "GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS" (8)
ERROR: 0:123: '' : shader storage buffer binding must be less than "GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS" (8)
ERROR: 0:382: 'ssboOffset' : undeclared identifier 
ERROR: 0:384: 'ssboOffset' : undeclared identifier 
ERROR: 0:393: 'thisA' : undeclared identifier 
ERROR: 0:393: 'ssboOffset' : undeclared identifier 
ERROR: 0:393: '[]' : integer expression required 
ERROR: 0:393: 'assign' :  cannot convert from '4-component vector of int' to 'float'
ERROR: 0:394: 'thisB' : undeclared identifier 
ERROR: 0:394: '[]' : integer expression required 
ERROR: 0:394: 'assign' :  cannot convert from '4-component vector of int' to 'float'
ERROR: 0:395: 'thisC' : undeclared identifier 
ERROR: 0:395
	at rs117.hd.Shader.compile(Shader.java:83)
	at rs117.hd.HdPlugin.initProgram(HdPlugin.java:669)
	at rs117.hd.HdPlugin.lambda$startUp$0(HdPlugin.java:497)
	... 9 common frames omitted`

**Comment by JorisBlanken** [comment]
Duplicate of #19
