### ISSUE TITLE
Shayzien Encampment not working

### ISSUE THREAD

**Issue by Murat40** [RS117/RLHD#77]
- OS: Windows 10
 - RuneLite version: 1.7.24
 - Launcher version: Idk

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

Hey I went to kill lizardmen in Shayzien, when i walked up from the fairy ring that is located next to the chasm of fire(DJR) I forgot my ranging pot and there is a bank in the shayzien encampment. The second I set foot in the shayzien encampment my game froze. I tried to disable the plugin but it did nothing, then I closed Runelite after which I opened it again with the plugin ON. The game did not load and the game froze on the menu screen after I clicked login. Then I restarted Runelite again without the plugin and I logged in. I tried to enable the plugin but did not budge after that i walked away from the area and it perfectly worked again.

I think there is something in the area that cannot load properly so it freezes/cannot load the plugin.

When i walked into the area:

2021-09-14 18:00:44 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Direct buffer memory
	at java.base/java.nio.Bits.reserveMemory(Unknown Source)
	at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at rs117.hd.GpuFloatBuffer.allocateDirect(GpuFloatBuffer.java:76)
	at rs117.hd.GpuFloatBuffer.ensureCapacity(GpuFloatBuffer.java:62)
	at rs117.hd.SceneUploader.pushFace(SceneUploader.java:1203)
	at rs117.hd.SceneUploader.uploadModel(SceneUploader.java:136)
	at rs117.hd.SceneUploader.upload(SceneUploader.java:214)
	at rs117.hd.SceneUploader.upload(SceneUploader.java:94)
	at rs117.hd.HdPlugin.uploadScene(HdPlugin.java:2031)
	at rs117.hd.HdPlugin.invokeOnMainThread(HdPlugin.java:2411)
	at rs117.hd.HdPlugin.onGameStateChanged(HdPlugin.java:2020)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:169)
	at client.yf(client.java:19313)
	at cc.ed(cc.java:2053)
	at client.i(client.java:1868)
	at at.jr(at.java:380)
	at at.run(at.java:359)
	at java.base/java.lang.Thread.run(Unknown Source)

When i could not load the plugin:

2021-09-14 18:02:54 [Client] ERROR rs117.hd.HdPlugin - Error starting HD plugin
java.lang.OutOfMemoryError: Direct buffer memory
	at java.base/java.nio.Bits.reserveMemory(Unknown Source)
	at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at rs117.hd.GpuFloatBuffer.allocateDirect(GpuFloatBuffer.java:76)
	at rs117.hd.GpuFloatBuffer.ensureCapacity(GpuFloatBuffer.java:62)
	at rs117.hd.SceneUploader.pushFace(SceneUploader.java:1203)
	at rs117.hd.SceneUploader.uploadModel(SceneUploader.java:136)
	at rs117.hd.SceneUploader.upload(SceneUploader.java:214)
	at rs117.hd.SceneUploader.upload(SceneUploader.java:94)
	at rs117.hd.HdPlugin.uploadScene(HdPlugin.java:2031)
	at rs117.hd.HdPlugin.invokeOnMainThread(HdPlugin.java:2411)
	at rs117.hd.HdPlugin.lambda$startUp$2(HdPlugin.java:548)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:195)
	at client.tq(client.java:43502)
	at client.aq(client.java)
	at at.b(at.java:406)
	at at.run(at.java:360)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by sosodev** [comment]
How much RAM do you have? Can you confirm that you're running the 64-bit client?
